name: Static Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: composer phpstan -- --error-format=github

      - name: Run Rector
        run: composer rector
